name: data-request
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - pandas
  - openpyxl
  - xlsxwriter
  - cf-units
  - cf_xarray
  - pooch
  - pyyaml
# for testing
  - pytest
  - pytest-cov
  - pytest-env
  - pip:
    - git+https://github.com/WCRP-CORDEX/data-request-tools.git
